sudo: false
language: python
cache: pip
git:
  depth: 3
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install: pip install coverage
script: 
  - coverage run --source=src setup.py test -q
  - coverage report
